version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./services/auth-service
    ports:
      - "5001:5000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - mongo
      - rabbitmq

  user-service:
    build: ./services/user-service
    ports:
      - "5002:5000"
    depends_on:
      - mongo

  gateway:
    image: nginx:alpine
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - user-service
